ALTER TYPE "PaymentBlockReason" ADD VALUE 'ACCOUNT_RESTRICTED';
ALTER TYPE "PaymentBlockReason" ADD VALUE 'PAYOUT_ON_HOLD';
ALTER TYPE "PaymentBlockReason" ADD VALUE 'INVALID_RECIPIENT';
ALTER TYPE "PaymentBlockReason" ADD VALUE 'INVALID_AMOUNT';
ALTER TYPE "PaymentBlockReason" ADD VALUE 'INVALID_REFERENCE';
ALTER TYPE "PaymentBlockReason" ADD VALUE 'PAYSTACK_VALIDATION';
